config/routes.rb
Rails.application.routes.draw do
  get 'your_orders'=> 'orders#your_orders'

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  post 'delete_from_cart' => 'cart#delete_from_cart'

  post 'order_complete' => 'cart#order_complete'

  post 'cancel_checkout' => 'cart#cancel_checkout'



  devise_for :users

  root 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  resources :categories
  resources :products



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

before_action :authenticate_user!, except: [:add_to_cart, :view_order]

  def add_to_cart

    @order = current_order

    if params[:quantity].blank?


      flash[:error] = "Select quantity for your item!"
      redirect_to root_url

    else
    line_item = @order.line_items.new(product_id: params[:product_id], quantity: params[:quantity])

    @order.save
    session[:order_id] = @order.id

    line_item.update(line_item_total: (line_item.quantity * line_item.product.price))

    redirect_to view_order_path
  end
  end

  def view_order
    @line_items = current_order.line_items
  end

  def delete_from_cart
    line_item = LineItem.find(params[:line_item_id])

    line_item.destroy

    redirect_to root_url
  end

  def cancel_checkout
    order = Order.find(params[:order_id])

    order.destroy

    redirect_to root_url
  end


  def checkout
    line_items = current_order.line_items

    if line_items.empty?
      redirect_to root_url

    else

      @order = current_order
      @order.update(user_id: current_user.id, subtotal: 0)

      line_items.each do |line_item|
        line_item.product.update(quantity: (line_item.product.quantity - line_item.quantity))

        if @order.order_items[line_item.product_id].nil?
           @order.order_items[line_item.product_id] = line_item.quantity
        else
           @order.order_items[line_item.product_id] += line_item.quantity
        end

        @order.subtotal += line_item.line_item_total
      end

      @order.save
      @order.update(sales_tax: (@order.subtotal * 0.08))
      @order.update(grand_total: (@order.sales_tax + @order.subtotal))


  end
  end

  def order_complete

    line_items = current_order.line_items

        @order = Order.find(params[:order_id])
        @amount = (@order.grand_total.to_f.round(2) * 100).to_i

        customer = Stripe::Customer.create(
          :email => params[:stripeEmail],
          :source  => params[:stripeToken]
        )

        charge = Stripe::Charge.create(
          :customer    => customer.id,
          :amount      => @amount,
          :description => 'Store Customer',
          :currency    => 'usd'
        )

        session.delete(:order_id)
        line_items.destroy_all


      rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to root_path
  end


end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h1>Let's Buy Some Goodies!</h1>

<h4> Your Order:</h4>

<table class= "table">
  <thead>
      <tr>
        <th> Product </th>
        <th> Quantity </th>
        <th> Unit Price </th>
        <th> Total Price </th>
      </tr>
  </thead>
  <tbody>
    <% @order.order_items.each do |key, value| %>
    <tr>
      <td><%= Product.find(key).name %></td>
      <td><%= value %></td>
      <td><%= number_to_currency Product.find(key).price %></td>
      <td><%= number_to_currency Product.find(key).price * value %></td>
    </tr>
    <% end %>
  </tbody>
</table>


<p> <strong> Sub Total: </strong> <%= number_to_currency @order.subtotal%><br></p>
<p> <strong> Tax Total: </strong> <%= number_to_currency @order.sales_tax%><br></p>
<p><strong> Order Total: </strong> <%= number_to_currency @order.grand_total%><br></p>

<div style="display:inline-block">
  <%= link_to "Empty my cart", cancel_checkout_path(order_id: @order.id), method: :post, class:"btn btn-danger", data: {confirm: "Are you sure you want to empty your cart?"} %>
</div>

<div style = 'display:inline-block;'>
  <%= form_tag order_complete_path do %>
  <div>
    <%= hidden_field_tag :order_id, @order.id %>
  </div>
<script src ="https://checkout.stripe.com/checkout.js"
class="stripe-button"
data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
data-description="Order #<%= @order.id %>"
data-amount = "<%= (@order.grand_total.to_f.round(2)* 100)%>"></script>
<% end %>
</div>

app/views/cart/order_complete.html.erb
<h2> Thank you for your order!</h2>

<h4>
<p><strong> Order #<%= @order.id %> will be shipping to you, <%= @order.user.email%> as soon as possible!</strong></p>



<p><strong>Customer: </strong></p>
<%= @order.user.name %><br>
<%= @order.user.address %><br>
<%= @order.user.state %><%= @order.user.zip %><br>
<%= @order.user.phone %><br>

</h4>

app/views/cart/view_order.html.erb
<h1> Shopping List </h1>

<div>
  <table class= "table">
    <thead>
      <tr>
          <th> Product</th>
          <th> Price</th>
          <th> Quantity</th>
          <th> Total Price</th>
          <th> Delete Item</th>
      </tr>
    </thead>
    <tbody>
      <% @line_items.each do |line_item|%>
      <tr>
        <td><%= line_item.product.name%></td>
        <td><%= number_to_currency(line_item.product.price)%></td>
        <td><%= line_item.quantity%></td>
        <td><%= number_to_currency(line_item.line_item_total)%></td>
        <td><%= link_to "Delete", delete_from_cart_path(line_item_id: line_item.id), method: :post, class: "btn btn-danger btn-xs", data: {confirm: "Are you sure your want to delete?"}%></td>
        </tr>
        <% end %>
    </tbody>
  </table>
</div>

<%= link_to "Go to checkout", checkout_path, class: "btn btn-success"%>
<%= link_to "Continue Shopping", root_path, class: "btn btn-info"%>